version: "3.9" # or a higher compatible version

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_local
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: sistema_carga_horaria
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    volumes:
      - mariadb_data:/var/lib/mariadb

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_local
    restart: always
    ports:
      - "7050:80"
    environment:
      PMA_HOST: mariadb
      PMA_USER: user
      PMA_PASSWORD: user123
    depends_on:
      - mariadb
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
