services:
  api-csharp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_csharp_local
    restart: always
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - shared_network

networks:
  shared_network:  # Use a mesma rede compartilhada do MariaDB
    external: true

